plugins {
    id 'application'
    id 'org.jetbrains.kotlin.jvm' version '2.3.20'
}

group 'com.improve_future.harmonica'
version rootProject.version

repositories {
    mavenCentral()
}

dependencies {
    def kotlinx_html_version = "0.7.3"
    implementation "org.jetbrains.kotlinx:kotlinx-html-jvm:${kotlinx_html_version}"
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_1_8)
    }
}

java {
    sourceCompatibility = '1.8'
    targetCompatibility = '1.8'
}

application {
    mainClass = "com.improve_future.harmonica.document.Main"
}