name: Dependency Graph Submission

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

permissions:
  actions: read
  contents: write

jobs:
  submit:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Submit dependency graph
        uses: gradle/actions/setup-gradle@v4
        with:
          dependency-graph: download-and-submit
          dependency-graph-continue-on-failure: false
